/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DelegateRouteImport } from './routes/delegate'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallsIdRouteImport } from './routes/calls.$id'
import { Route as ApiSwapQuoteRouteImport } from './routes/api.swap-quote'
import { Route as ApiMarketsRouteImport } from './routes/api.markets'
import { Route as ApiGenerateAgentImageRouteImport } from './routes/api.generate-agent-image'
import { Route as ApiCircleWebhookRouteImport } from './routes/api.circle-webhook'
import { Route as ApiAgentWorkerRouteImport } from './routes/api.agent-worker'
import { Route as AgentIdRouteImport } from './routes/agent.$id'
import { Route as ApiRuntimeWithdrawalsRouteImport } from './routes/api.runtime.withdrawals'
import { Route as ApiRuntimeDelegationsRouteImport } from './routes/api.runtime.delegations'
import { Route as ApiRuntimeDatasetRouteImport } from './routes/api.runtime.dataset'
import { Route as ApiRuntimeAgentsRouteImport } from './routes/api.runtime.agents'
import { Route as ApiAgentMetadataIdRouteImport } from './routes/api.agent-metadata.$id'
import { Route as ApiRuntimeMetadataIdRouteImport } from './routes/api.runtime.metadata.$id'
import { Route as ApiRuntimeCallsIdRouteImport } from './routes/api.runtime.calls.$id'
import { Route as ApiRuntimeAgentsIdDeploymentRouteImport } from './routes/api.runtime.agents.$id.deployment'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegateRoute = DelegateRouteImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIdRoute = CallsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CallsRoute,
} as any)
const ApiSwapQuoteRoute = ApiSwapQuoteRouteImport.update({
  id: '/api/swap-quote',
  path: '/api/swap-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketsRoute = ApiMarketsRouteImport.update({
  id: '/api/markets',
  path: '/api/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateAgentImageRoute = ApiGenerateAgentImageRouteImport.update({
  id: '/api/generate-agent-image',
  path: '/api/generate-agent-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCircleWebhookRoute = ApiCircleWebhookRouteImport.update({
  id: '/api/circle-webhook',
  path: '/api/circle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentWorkerRoute = ApiAgentWorkerRouteImport.update({
  id: '/api/agent-worker',
  path: '/api/agent-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeWithdrawalsRoute = ApiRuntimeWithdrawalsRouteImport.update({
  id: '/api/runtime/withdrawals',
  path: '/api/runtime/withdrawals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeDelegationsRoute = ApiRuntimeDelegationsRouteImport.update({
  id: '/api/runtime/delegations',
  path: '/api/runtime/delegations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeDatasetRoute = ApiRuntimeDatasetRouteImport.update({
  id: '/api/runtime/dataset',
  path: '/api/runtime/dataset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeAgentsRoute = ApiRuntimeAgentsRouteImport.update({
  id: '/api/runtime/agents',
  path: '/api/runtime/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentMetadataIdRoute = ApiAgentMetadataIdRouteImport.update({
  id: '/api/agent-metadata/$id',
  path: '/api/agent-metadata/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeMetadataIdRoute = ApiRuntimeMetadataIdRouteImport.update({
  id: '/api/runtime/metadata/$id',
  path: '/api/runtime/metadata/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeCallsIdRoute = ApiRuntimeCallsIdRouteImport.update({
  id: '/api/runtime/calls/$id',
  path: '/api/runtime/calls/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeAgentsIdDeploymentRoute =
  ApiRuntimeAgentsIdDeploymentRouteImport.update({
    id: '/$id/deployment',
    path: '/$id/deployment',
    getParentRoute: () => ApiRuntimeAgentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/arena': typeof ArenaRoute
  '/calls': typeof CallsRouteWithChildren
  '/delegate': typeof DelegateRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/swap': typeof SwapRoute
  '/agent/$id': typeof AgentIdRoute
  '/api/agent-worker': typeof ApiAgentWorkerRoute
  '/api/circle-webhook': typeof ApiCircleWebhookRoute
  '/api/generate-agent-image': typeof ApiGenerateAgentImageRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/swap-quote': typeof ApiSwapQuoteRoute
  '/calls/$id': typeof CallsIdRoute
  '/api/agent-metadata/$id': typeof ApiAgentMetadataIdRoute
  '/api/runtime/agents': typeof ApiRuntimeAgentsRouteWithChildren
  '/api/runtime/dataset': typeof ApiRuntimeDatasetRoute
  '/api/runtime/delegations': typeof ApiRuntimeDelegationsRoute
  '/api/runtime/withdrawals': typeof ApiRuntimeWithdrawalsRoute
  '/api/runtime/calls/$id': typeof ApiRuntimeCallsIdRoute
  '/api/runtime/metadata/$id': typeof ApiRuntimeMetadataIdRoute
  '/api/runtime/agents/$id/deployment': typeof ApiRuntimeAgentsIdDeploymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/arena': typeof ArenaRoute
  '/calls': typeof CallsRouteWithChildren
  '/delegate': typeof DelegateRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/swap': typeof SwapRoute
  '/agent/$id': typeof AgentIdRoute
  '/api/agent-worker': typeof ApiAgentWorkerRoute
  '/api/circle-webhook': typeof ApiCircleWebhookRoute
  '/api/generate-agent-image': typeof ApiGenerateAgentImageRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/swap-quote': typeof ApiSwapQuoteRoute
  '/calls/$id': typeof CallsIdRoute
  '/api/agent-metadata/$id': typeof ApiAgentMetadataIdRoute
  '/api/runtime/agents': typeof ApiRuntimeAgentsRouteWithChildren
  '/api/runtime/dataset': typeof ApiRuntimeDatasetRoute
  '/api/runtime/delegations': typeof ApiRuntimeDelegationsRoute
  '/api/runtime/withdrawals': typeof ApiRuntimeWithdrawalsRoute
  '/api/runtime/calls/$id': typeof ApiRuntimeCallsIdRoute
  '/api/runtime/metadata/$id': typeof ApiRuntimeMetadataIdRoute
  '/api/runtime/agents/$id/deployment': typeof ApiRuntimeAgentsIdDeploymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/arena': typeof ArenaRoute
  '/calls': typeof CallsRouteWithChildren
  '/delegate': typeof DelegateRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/swap': typeof SwapRoute
  '/agent/$id': typeof AgentIdRoute
  '/api/agent-worker': typeof ApiAgentWorkerRoute
  '/api/circle-webhook': typeof ApiCircleWebhookRoute
  '/api/generate-agent-image': typeof ApiGenerateAgentImageRoute
  '/api/markets': typeof ApiMarketsRoute
  '/api/swap-quote': typeof ApiSwapQuoteRoute
  '/calls/$id': typeof CallsIdRoute
  '/api/agent-metadata/$id': typeof ApiAgentMetadataIdRoute
  '/api/runtime/agents': typeof ApiRuntimeAgentsRouteWithChildren
  '/api/runtime/dataset': typeof ApiRuntimeDatasetRoute
  '/api/runtime/delegations': typeof ApiRuntimeDelegationsRoute
  '/api/runtime/withdrawals': typeof ApiRuntimeWithdrawalsRoute
  '/api/runtime/calls/$id': typeof ApiRuntimeCallsIdRoute
  '/api/runtime/metadata/$id': typeof ApiRuntimeMetadataIdRoute
  '/api/runtime/agents/$id/deployment': typeof ApiRuntimeAgentsIdDeploymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/arena'
    | '/calls'
    | '/delegate'
    | '/docs'
    | '/login'
    | '/markets'
    | '/portfolio'
    | '/register'
    | '/swap'
    | '/agent/$id'
    | '/api/agent-worker'
    | '/api/circle-webhook'
    | '/api/generate-agent-image'
    | '/api/markets'
    | '/api/swap-quote'
    | '/calls/$id'
    | '/api/agent-metadata/$id'
    | '/api/runtime/agents'
    | '/api/runtime/dataset'
    | '/api/runtime/delegations'
    | '/api/runtime/withdrawals'
    | '/api/runtime/calls/$id'
    | '/api/runtime/metadata/$id'
    | '/api/runtime/agents/$id/deployment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/arena'
    | '/calls'
    | '/delegate'
    | '/docs'
    | '/login'
    | '/markets'
    | '/portfolio'
    | '/register'
    | '/swap'
    | '/agent/$id'
    | '/api/agent-worker'
    | '/api/circle-webhook'
    | '/api/generate-agent-image'
    | '/api/markets'
    | '/api/swap-quote'
    | '/calls/$id'
    | '/api/agent-metadata/$id'
    | '/api/runtime/agents'
    | '/api/runtime/dataset'
    | '/api/runtime/delegations'
    | '/api/runtime/withdrawals'
    | '/api/runtime/calls/$id'
    | '/api/runtime/metadata/$id'
    | '/api/runtime/agents/$id/deployment'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/arena'
    | '/calls'
    | '/delegate'
    | '/docs'
    | '/login'
    | '/markets'
    | '/portfolio'
    | '/register'
    | '/swap'
    | '/agent/$id'
    | '/api/agent-worker'
    | '/api/circle-webhook'
    | '/api/generate-agent-image'
    | '/api/markets'
    | '/api/swap-quote'
    | '/calls/$id'
    | '/api/agent-metadata/$id'
    | '/api/runtime/agents'
    | '/api/runtime/dataset'
    | '/api/runtime/delegations'
    | '/api/runtime/withdrawals'
    | '/api/runtime/calls/$id'
    | '/api/runtime/metadata/$id'
    | '/api/runtime/agents/$id/deployment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArenaRoute: typeof ArenaRoute
  CallsRoute: typeof CallsRouteWithChildren
  DelegateRoute: typeof DelegateRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  PortfolioRoute: typeof PortfolioRoute
  RegisterRoute: typeof RegisterRoute
  SwapRoute: typeof SwapRoute
  AgentIdRoute: typeof AgentIdRoute
  ApiAgentWorkerRoute: typeof ApiAgentWorkerRoute
  ApiCircleWebhookRoute: typeof ApiCircleWebhookRoute
  ApiGenerateAgentImageRoute: typeof ApiGenerateAgentImageRoute
  ApiMarketsRoute: typeof ApiMarketsRoute
  ApiSwapQuoteRoute: typeof ApiSwapQuoteRoute
  ApiAgentMetadataIdRoute: typeof ApiAgentMetadataIdRoute
  ApiRuntimeAgentsRoute: typeof ApiRuntimeAgentsRouteWithChildren
  ApiRuntimeDatasetRoute: typeof ApiRuntimeDatasetRoute
  ApiRuntimeDelegationsRoute: typeof ApiRuntimeDelegationsRoute
  ApiRuntimeWithdrawalsRoute: typeof ApiRuntimeWithdrawalsRoute
  ApiRuntimeCallsIdRoute: typeof ApiRuntimeCallsIdRoute
  ApiRuntimeMetadataIdRoute: typeof ApiRuntimeMetadataIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegate': {
      id: '/delegate'
      path: '/delegate'
      fullPath: '/delegate'
      preLoaderRoute: typeof DelegateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$id': {
      id: '/calls/$id'
      path: '/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof CallsIdRouteImport
      parentRoute: typeof CallsRoute
    }
    '/api/swap-quote': {
      id: '/api/swap-quote'
      path: '/api/swap-quote'
      fullPath: '/api/swap-quote'
      preLoaderRoute: typeof ApiSwapQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/markets': {
      id: '/api/markets'
      path: '/api/markets'
      fullPath: '/api/markets'
      preLoaderRoute: typeof ApiMarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-agent-image': {
      id: '/api/generate-agent-image'
      path: '/api/generate-agent-image'
      fullPath: '/api/generate-agent-image'
      preLoaderRoute: typeof ApiGenerateAgentImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/circle-webhook': {
      id: '/api/circle-webhook'
      path: '/api/circle-webhook'
      fullPath: '/api/circle-webhook'
      preLoaderRoute: typeof ApiCircleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-worker': {
      id: '/api/agent-worker'
      path: '/api/agent-worker'
      fullPath: '/api/agent-worker'
      preLoaderRoute: typeof ApiAgentWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/withdrawals': {
      id: '/api/runtime/withdrawals'
      path: '/api/runtime/withdrawals'
      fullPath: '/api/runtime/withdrawals'
      preLoaderRoute: typeof ApiRuntimeWithdrawalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/delegations': {
      id: '/api/runtime/delegations'
      path: '/api/runtime/delegations'
      fullPath: '/api/runtime/delegations'
      preLoaderRoute: typeof ApiRuntimeDelegationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/dataset': {
      id: '/api/runtime/dataset'
      path: '/api/runtime/dataset'
      fullPath: '/api/runtime/dataset'
      preLoaderRoute: typeof ApiRuntimeDatasetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/agents': {
      id: '/api/runtime/agents'
      path: '/api/runtime/agents'
      fullPath: '/api/runtime/agents'
      preLoaderRoute: typeof ApiRuntimeAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-metadata/$id': {
      id: '/api/agent-metadata/$id'
      path: '/api/agent-metadata/$id'
      fullPath: '/api/agent-metadata/$id'
      preLoaderRoute: typeof ApiAgentMetadataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/metadata/$id': {
      id: '/api/runtime/metadata/$id'
      path: '/api/runtime/metadata/$id'
      fullPath: '/api/runtime/metadata/$id'
      preLoaderRoute: typeof ApiRuntimeMetadataIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/calls/$id': {
      id: '/api/runtime/calls/$id'
      path: '/api/runtime/calls/$id'
      fullPath: '/api/runtime/calls/$id'
      preLoaderRoute: typeof ApiRuntimeCallsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/agents/$id/deployment': {
      id: '/api/runtime/agents/$id/deployment'
      path: '/$id/deployment'
      fullPath: '/api/runtime/agents/$id/deployment'
      preLoaderRoute: typeof ApiRuntimeAgentsIdDeploymentRouteImport
      parentRoute: typeof ApiRuntimeAgentsRoute
    }
  }
}

interface CallsRouteChildren {
  CallsIdRoute: typeof CallsIdRoute
}

const CallsRouteChildren: CallsRouteChildren = {
  CallsIdRoute: CallsIdRoute,
}

const CallsRouteWithChildren = CallsRoute._addFileChildren(CallsRouteChildren)

interface ApiRuntimeAgentsRouteChildren {
  ApiRuntimeAgentsIdDeploymentRoute: typeof ApiRuntimeAgentsIdDeploymentRoute
}

const ApiRuntimeAgentsRouteChildren: ApiRuntimeAgentsRouteChildren = {
  ApiRuntimeAgentsIdDeploymentRoute: ApiRuntimeAgentsIdDeploymentRoute,
}

const ApiRuntimeAgentsRouteWithChildren =
  ApiRuntimeAgentsRoute._addFileChildren(ApiRuntimeAgentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArenaRoute: ArenaRoute,
  CallsRoute: CallsRouteWithChildren,
  DelegateRoute: DelegateRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  PortfolioRoute: PortfolioRoute,
  RegisterRoute: RegisterRoute,
  SwapRoute: SwapRoute,
  AgentIdRoute: AgentIdRoute,
  ApiAgentWorkerRoute: ApiAgentWorkerRoute,
  ApiCircleWebhookRoute: ApiCircleWebhookRoute,
  ApiGenerateAgentImageRoute: ApiGenerateAgentImageRoute,
  ApiMarketsRoute: ApiMarketsRoute,
  ApiSwapQuoteRoute: ApiSwapQuoteRoute,
  ApiAgentMetadataIdRoute: ApiAgentMetadataIdRoute,
  ApiRuntimeAgentsRoute: ApiRuntimeAgentsRouteWithChildren,
  ApiRuntimeDatasetRoute: ApiRuntimeDatasetRoute,
  ApiRuntimeDelegationsRoute: ApiRuntimeDelegationsRoute,
  ApiRuntimeWithdrawalsRoute: ApiRuntimeWithdrawalsRoute,
  ApiRuntimeCallsIdRoute: ApiRuntimeCallsIdRoute,
  ApiRuntimeMetadataIdRoute: ApiRuntimeMetadataIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
