/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DelegateRouteImport } from './routes/delegate'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallsIdRouteImport } from './routes/calls.$id'
import { Route as ApiCircleWebhookRouteImport } from './routes/api.circle-webhook'
import { Route as ApiAgentWorkerRouteImport } from './routes/api.agent-worker'
import { Route as AgentIdRouteImport } from './routes/agent.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DelegateRoute = DelegateRouteImport.update({
  id: '/delegate',
  path: '/delegate',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsIdRoute = CallsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CallsRoute,
} as any)
const ApiCircleWebhookRoute = ApiCircleWebhookRouteImport.update({
  id: '/api/circle-webhook',
  path: '/api/circle-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentWorkerRoute = ApiAgentWorkerRouteImport.update({
  id: '/api/agent-worker',
  path: '/api/agent-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/arena': typeof ArenaRoute
  '/calls': typeof CallsRouteWithChildren
  '/delegate': typeof DelegateRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/api/agent-worker': typeof ApiAgentWorkerRoute
  '/api/circle-webhook': typeof ApiCircleWebhookRoute
  '/calls/$id': typeof CallsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/arena': typeof ArenaRoute
  '/calls': typeof CallsRouteWithChildren
  '/delegate': typeof DelegateRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/api/agent-worker': typeof ApiAgentWorkerRoute
  '/api/circle-webhook': typeof ApiCircleWebhookRoute
  '/calls/$id': typeof CallsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/arena': typeof ArenaRoute
  '/calls': typeof CallsRouteWithChildren
  '/delegate': typeof DelegateRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/register': typeof RegisterRoute
  '/agent/$id': typeof AgentIdRoute
  '/api/agent-worker': typeof ApiAgentWorkerRoute
  '/api/circle-webhook': typeof ApiCircleWebhookRoute
  '/calls/$id': typeof CallsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/arena'
    | '/calls'
    | '/delegate'
    | '/docs'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/agent/$id'
    | '/api/agent-worker'
    | '/api/circle-webhook'
    | '/calls/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/arena'
    | '/calls'
    | '/delegate'
    | '/docs'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/agent/$id'
    | '/api/agent-worker'
    | '/api/circle-webhook'
    | '/calls/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/arena'
    | '/calls'
    | '/delegate'
    | '/docs'
    | '/login'
    | '/portfolio'
    | '/register'
    | '/agent/$id'
    | '/api/agent-worker'
    | '/api/circle-webhook'
    | '/calls/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArenaRoute: typeof ArenaRoute
  CallsRoute: typeof CallsRouteWithChildren
  DelegateRoute: typeof DelegateRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  RegisterRoute: typeof RegisterRoute
  AgentIdRoute: typeof AgentIdRoute
  ApiAgentWorkerRoute: typeof ApiAgentWorkerRoute
  ApiCircleWebhookRoute: typeof ApiCircleWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delegate': {
      id: '/delegate'
      path: '/delegate'
      fullPath: '/delegate'
      preLoaderRoute: typeof DelegateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls/$id': {
      id: '/calls/$id'
      path: '/$id'
      fullPath: '/calls/$id'
      preLoaderRoute: typeof CallsIdRouteImport
      parentRoute: typeof CallsRoute
    }
    '/api/circle-webhook': {
      id: '/api/circle-webhook'
      path: '/api/circle-webhook'
      fullPath: '/api/circle-webhook'
      preLoaderRoute: typeof ApiCircleWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-worker': {
      id: '/api/agent-worker'
      path: '/api/agent-worker'
      fullPath: '/api/agent-worker'
      preLoaderRoute: typeof ApiAgentWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CallsRouteChildren {
  CallsIdRoute: typeof CallsIdRoute
}

const CallsRouteChildren: CallsRouteChildren = {
  CallsIdRoute: CallsIdRoute,
}

const CallsRouteWithChildren = CallsRoute._addFileChildren(CallsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArenaRoute: ArenaRoute,
  CallsRoute: CallsRouteWithChildren,
  DelegateRoute: DelegateRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  RegisterRoute: RegisterRoute,
  AgentIdRoute: AgentIdRoute,
  ApiAgentWorkerRoute: ApiAgentWorkerRoute,
  ApiCircleWebhookRoute: ApiCircleWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
